### ISSUE TITLE
折线图支持负数吗

### ISSUE THREAD

**Issue by 360573078** [xuuhan/HXCharts#1]
我的折线图里面有正数也有负数！

**Comment by xuuhan** [comment]
不支持，我周末抽时间加上

**Comment by xuuhan** [comment]
不支持,我周末抽空加一下吧，周一到周五实在太忙了

**Comment by xuuhan** [comment]
你好，你需要的支持负数折线图是什么样式需求？负数和正数的线颜色需要分别设置吗，需要填充效果吗

**Comment by 360573078** [comment]
谢谢，您真好！
就是如果一堆数组里面有正数和负数，就把0放在纵轴中间。

**Comment by xuuhan** [comment]
OK 因为晚上也有工作 正在抽空做 周末上传
