### ISSUE TITLE
方法暴露

### ISSUE THREAD

**Issue by ZClee128** [xuuhan/HXCharts#6]
希望可以暴露一个方法设置柱状图上的值可以旋转45度显示，设置每个柱状图的间隔，虽然我在demo上改了你的方法，但是效果不是很理想

**Comment by ZClee128** [comment]
还有一个问题，可以设置默认显示特定的柱状，嘻嘻

**Comment by xuuhan** [comment]
特定的柱状是啥意思

**Comment by ZClee128** [comment]
我重新写了一个问题，解释这个特定柱状的意思

**Comment by xuuhan** [comment]
旋转角度自定义已上传
