### ISSUE TITLE
选中显示

### ISSUE THREAD

**Issue by ZClee128** [xuuhan/HXCharts#7]
希望有一个办法是可以设置显示的一个柱状显示在当前页面，就是月份，默认是展示1，2，3，4月，但是我想展示7月在当前，然后1，2，3，4会往前，因为现在你的柱状图是可以滑动的，不知道大神能不能实现

**Comment by xuuhan** [comment]
增加了一个初始偏移量的参数，需要显示在哪你根据你的间距和柱状宽度算一下就行
